[package]
name = "cli"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["cargo", "derive"] }
jarvis = { path = "../core" }
